on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Build'
        uses: shalzz/zola-deploy-action@v0.15.3
        env:
          BUILD_DIR: .
          TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          BUILD_ONLY: true
      - name: 'Deploy'
        if: (! github.head_ref) && (github.ref == 'refs/heads/main')
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: public
          clean: true
          single-commit: true
